server:
  port: 9091
spring:
  application:
    name: Orderservices
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
  instance:
    hostname: localhost